# Generated by Django 4.0 on 2021-12-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
